# Generated by Django 5.0.4 on 2024-05-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
